### ISSUE TITLE
Uncaught Invariant Violation: Hooks can only be 

### ISSUE THREAD

**Issue by alexec** [atomiks/tippyjs-react#73] opened 2019-04-01 17:59 UTC
```
react.development.js:88 Uncaught Invariant Violation: Hooks can only be called inside the body of a function component. (https://fb.me/react-invalid-hook-call)
    at invariant (http://localhost:4000/main.a6b75653f0309809b820.js:52363:15)
    at resolveDispatcher (http://localhost:4000/main.a6b75653f0309809b820.js:53711:28)
    at useState (http://localhost:4000/main.a6b75653f0309809b820.js:53736:20)
    at Tippy (http://localhost:4000/main.a6b75653f0309809b820.js:504:73)
    at renderWithHooks (http://localhost:4000/main.a6b75653f0309809b820.js:176693:18)
    at mountIndeterminateComponent (http://localhost:4000/main.a6b75653f0309809b820.js:178670:13)
    at beginWork (http://localhost:4000/main.a6b75653f0309809b820.js:179275:16)
    at performUnitOfWork (http://localhost:4000/main.a6b75653f0309809b820.js:182962:12)
    at workLoop (http://localhost:4000/main.a6b75653f0309809b820.js:183002:24)
    at HTMLUnknownElement.callCallback (http://localhost:4000/main.a6b75653f0309809b820.js:164003:14)
invariant @ react.development.js:88
resolveDispatcher @ react.development.js:1436
useState @ react.development.js:1461
Tippy @ Tippy.js:36
renderWithHooks @ react-dom.development.js:12839
mountIndeterminateComponent @ react-dom.development.js:14816
beginWork @ react-dom.development.js:15421
performUnitOfWork @ react-dom.development.js:19108
workLoop @ react-dom.development.js:19148
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
replayUnitOfWork @ react-dom.development.js:18374
renderRoot @ react-dom.development.js:19264
performWorkOnRoot @ react-dom.development.js:20138
performWork @ react-dom.development.js:20050
performSyncWork @ react-dom.development.js:20024
requestWork @ react-dom.development.js:19893
scheduleWork @ react-dom.development.js:19707
scheduleRootUpdate @ react-dom.development.js:20368
updateContainerAtExpirationTime @ react-dom.development.js:20396
updateContainer @ react-dom.development.js:20453
./node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render @ react-dom.development.js:20749
(anonymous) @ react-dom.development.js:20886
unbatchedUpdates @ react-dom.development.js:20255
legacyRenderSubtreeIntoContainer @ react-dom.development.js:20882
render @ react-dom.development.js:20951
(anonymous) @ index.tsx:5
./src/app/index.tsx @ index.tsx:13
__webpack_require__ @ bootstrap:63
0 @ view-preferences-service.ts:100
__webpack_require__ @ bootstrap:63
(anonymous) @ bootstrap:195
(anonymous) @ bootstrap:195
Show 4 more frames
3react-dom.development.js:16913 The above error occurred in the <Tippy> component:
    in Tippy
    in ForwardRef(TippyWrapper)
    in div
    in div
    in div
    in NavBar
    in div
    in Layout (created by Route)
    in Route (created by App)
    in Switch (created by App)
    in Router (created by App)
    in App

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://fb.me/react-error-boundaries to learn more about error boundaries.
logCapturedError @ react-dom.development.js:16913
logError @ react-dom.development.js:16949
update.callback @ react-dom.development.js:17861
callCallback @ react-dom.development.js:16229
commitUpdateEffects @ react-dom.development.js:16268
commitUpdateQueue @ react-dom.development.js:16259
commitLifeCycles @ react-dom.development.js:17179
commitAllLifeCycles @ react-dom.development.js:18532
callCallback @ react-dom.development.js:149
invokeGuardedCallbackDev @ react-dom.development.js:199
invokeGuardedCallback @ react-dom.development.js:256
commitRoot @ react-dom.development.js:18744
(anonymous) @ react-dom.development.js:20214
unstable_runWithPriority @ scheduler.development.js:255
completeRoot @ react-dom.development.js:20213
performWorkOnRoot @ react-dom.development.js:20142
performWork @ react-dom.development.js:20050
performSyncWork @ react-dom.development.js:20024
requestWork @ react-dom.development.js:19893
scheduleWork @ react-dom.development.js:19707
scheduleRootUpdate @ react-dom.development.js:20368
updateContainerAtExpirationTime @ react-dom.development.js:20396
updateContainer @ react-dom.development.js:20453
./node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render @ react-dom.development.js:20749
(anonymous) @ react-dom.development.js:20886
unbatchedUpdates @ react-dom.development.js:20255
legacyRenderSubtreeIntoContainer @ react-dom.development.js:20882
render @ react-dom.development.js:20951
(anonymous) @ index.tsx:5
./src/app/index.tsx @ index.tsx:13
__webpack_require__ @ bootstrap:63
0 @ view-preferences-service.ts:100
__webpack_require__ @ bootstrap:63
(anonymous) @ bootstrap:195
(anonymous) @ bootstrap:195
Show 5 more frames
react.development.js:88 Uncaught Invariant Violation: Hooks can only be called inside the body of a function component. (https://fb.me/react-invalid-hook-call)
    at invariant (http://localhost:4000/main.a6b75653f0309809b820.js:52363:15)
    at resolveDispatcher (http://localhost:4000/main.a6b75653f0309809b820.js:53711:28)
    at useState (http://localhost:4000/main.a6b75653f0309809b820.js:53736:20)
    at Tippy (http://localhost:4000/main.a6b75653f0309809b820.js:504:73)
    at renderWithHooks (http://localhost:4000/main.a6b75653f0309809b820.js:176693:18)
    at mountIndeterminateComponent (http://localhost:4000/main.a6b75653f0309809b820.js:178670:13)
    at beginWork (http://localhost:4000/main.a6b75653f0309809b820.js:179275:16)
    at performUnitOfWork (http://localhost:4000/main.a6b75653f0309809b820.js:182962:12)
    at workLoop (http://localhost:4000/main.a6b75653f0309809b820.js:183002:24)
    at renderRoot (http://localhost:4000/main.a6b75653f0309809b820.js:183085:7)
invariant @ react.development.js:88
resolveDispatcher @ react.development.js:1436
useState @ react.development.js:1461
Tippy @ Tippy.js:36
renderWithHooks @ react-dom.development.js:12839
mountIndeterminateComponent @ react-dom.development.js:14816
beginWork @ react-dom.development.js:15421
performUnitOfWork @ react-dom.development.js:19108
workLoop @ react-dom.development.js:19148
renderRoot @ react-dom.development.js:19231
performWorkOnRoot @ react-dom.development.js:20138
performWork @ react-dom.development.js:20050
performSyncWork @ react-dom.development.js:20024
requestWork @ react-dom.development.js:19893
scheduleWork @ react-dom.development.js:19707
scheduleRootUpdate @ react-dom.development.js:20368
updateContainerAtExpirationTime @ react-dom.development.js:20396
updateContainer @ react-dom.development.js:20453
./node_modules/react-dom/cjs/react-dom.development.js.ReactRoot.render @ react-dom.development.js:20749
(anonymous) @ react-dom.development.js:20886
unbatchedUpdates @ react-dom.development.js:20255
legacyRenderSubtreeIntoContainer @ react-dom.development.js:20882
render @ react-dom.development.js:20951
(anonymous) @ index.tsx:5
./src/app/index.tsx @ index.tsx:13
__webpack_require__ @ bootstrap:63
0 @ view-preferences-service.ts:100
__webpack_require__ @ bootstrap:63
(anonymous) @ bootstrap:195
(anonymous) @ bootstrap:195
```

**Comment by EmmaRamirez** [comment] 2019-04-14 07:29
What was the answer to this? Currently experiencing it

**Comment by atomiks** [comment] 2019-04-14 07:38
@EmmaRamirez 

![what did you see xkcd](https://imgs.xkcd.com/comics/wisdom_of_the_ancients.png)

Post some code, we might be able to solve this for others who experience this issue as well ✌️

**Comment by Haofei** [comment] 2019-05-17 20:36
got a similar error. however this is a huge project with lots dependencies

i fallback to the class based component with latest tippy as a workaround.

**Comment by ivdma** [comment] 2019-11-05 16:08
Anyone solved this problem yet? Or at least found the reason?

**Comment by wbharding** [comment] 2020-10-24 14:54
Been struggling against this for most of my morning. In my case I've ascertained that the order in which packs are loaded seems to trigger this. If the component with tippy isn't the first pack tag that gets loaded on my page, then I get this error; if the tippy-bearing component is the first pack tag, then it works fine. Ugh.

**Comment by alexec** [comment] 2021-01-08 20:09
This is just a canonical problem of how can Yarn waste half a day of my time with an interminable dependency problem.  Sady, the easiest solution to every yarn dependency problem seems to be: remove the dependency.

```
yarn remove "@tippy.js/react"
```

**Comment by alexec** [comment] 2021-09-07 18:41
Here I am, 2 years later, with the same problem.

**Comment by KubaJastrz** [comment] 2021-09-07 18:46
Hello @alexec, please make a codesandbox reproduction and I'll gladly take look at it :)

**Comment by alexec** [comment] 2021-09-07 19:13
I'd love too, but I'm afraid it is not a priority

**Comment by MathiasHoeyrup** [comment] 2021-09-15 11:20
I just succeeded by changing both the react and the react-dom version to 16.14.0. 

`
"react": "^16.14.0",
"react-dom": "^16.14.0"
`

**Comment by atomiks** [comment] 2021-11-06 05:57
I'm going to close this one out because it's based on a user's environment, and not this library itself. If you're going insane and can't debug/fix it, remove this library and install `tippy.js` core and create your own small wrapper around it for React. `react-tippy` is very outdated with many bugs, I wouldn't use it.

**Closed by atomiks** 2021-11-06 05:57 UTC
